import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import { ReactNode } from 'react'

import { ConfigProvider } from '@/providers/ConfigProvider'
import { FramerMotionProvider } from '@/providers/FramerMotionProvider'
import TanStackQueryProvider from '@/providers/TanStackQueryProvider'
import { ThemeProvider } from '@/providers/ThemeProvider'
import { Toaster } from '@/providers/ToastProvider/ToastSonner'
import { YandexMapsProvider } from '@/providers/YandexMapsProvider'

import '@/styles/globals.css'
import '@/styles/theme.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

interface RootLayoutProps {
	children: ReactNode
}

export default async function RootLayout({ children }: RootLayoutProps) {
	const locale = await getLocale()
	const messages = await getMessages()

	return (
		<html lang={locale} suppressHydrationWarning>
			<body>
				<ConfigProvider />
				<ThemeProvider>
					<NextIntlClientProvider messages={messages}>
						<FramerMotionProvider>
							<TanStackQueryProvider>
								<YandexMapsProvider>
									<Toaster />
									{children}
								</YandexMapsProvider>
							</TanStackQueryProvider>
						</FramerMotionProvider>
					</NextIntlClientProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
